name: Deploy MultiDocker
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t josefnagy/vue-test -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true josefnagy/vue-test npm test

            - run: docker build -t josefnagy/multi-client ./client
            - run: docker build -t josefnagy/multi-nginx ./nginx
            - run: docker build -t josefnagy/multi-server ./server
            - run: docker build -t josefnagy/multi-worker ./worker

            - run: docker push josefnagy/multi-client
            - run: docker push josefnagy/multi-nginx
            - run: docker push josefnagy/multi-server
            - run: docker push josefnagy/multi-worker
